### ISSUE TITLE
Ability to return source YAML node

### ISSUE THREAD

**Issue by alexgorbatchev** [Xiphe/yaml-doc-query#1]
This is a pretty great module, however getting `node.toJSON()` is limiting its usefulness IMO. I would really like to see an option to get the raw `YAML.Node`.

**Comment by alexgorbatchev** [comment]
I have a simplified fork over at https://www.npmjs.com/package/@yaml-tools/query

**Comment by Xiphe** [comment]
Cool! I understand. Not sure if I'll further maintain this, might as well switch to your fork in the future :)
